### ISSUE TITLE
Better way to deal with unusual JSON data

### ISSUE THREAD

**Issue by sutram** [pipelinedb/pipeline_kafka#5]
Currently JSON data that contains escaped invalid characters has to be dealt in an unusual way by this extension. For example, the following JSON

{"playback_viewId": "**\x**22cGF0aFVSST0lMkZMSVZFJTJGMTAwNiUyRnNzJTJGcHIlMkZBTUNfSEQuaXNtbCUyRiomcGF0aFVSST0lMkZjZG4lMkZpbWFnZXNlcnZlciUyRiomcGF0aFVSST0lMkZjZG4lMkZlcGdzJTJGKiZwYXRoVVJJPSUyRmNkbiUyRm5tZCUyRiomcGF0aFVSST0lMkZjZG4lMkZuYXRpb25hbG5hdmlnYXRpb24lMkYqJnBhdGhVUkk9JTJGYWRzJTJGKiZmbj1zaGE1MTImZXhwaXJ5PTE0NTY0NTU2MTgmWC1jbGllbnRJcD03NC4xMjkuNTEuMTUxJlgtY3VzdG9tZXJHdWlkPUI4NzBFQUIyLTI3RjktRTBFQS1EQTA4LTZFQjk4RTM5MUM2OCZYLXNlc3Npb25JZD1hZGM3Yzk2MC1kYmM1LTExZTUtYWY1ZS1iNTNhMWIzZDVmZjEmWC1hcGlLZXk9NzJjMDc2NDgtZWExNC00NGYyLWFiZWQtZTM4MjYzNTgwYjVjJlgtcmVxdWVzdElkPTAwMDAwMTUyZTYyMzllMjgtMTE4MmZjNjksOWVhMTM0Yzg0OWFjYjQ3ZWY1MThkODJmMjRlZWVlYjBjMzRmNDk2ZGI3MDA3ZDIxOWZiOTU0NGU2ZDAzMWZiNTgyZDQ5NzQ1ODk3MDljMGIwODYyNDdiZjc0ZmIyMTgwYzczNzhhNmY5YTY0YjFkZjc0NDQwNzIyYTI5ZDk0NTU=\x22", "datatransfer_uri": "/LIVE/1006/ss/pr/AMC_HD.isml/QualityLevels(20000)/FragmentInfo(textstream301_und=512169853380000)", "datatransfer_userAgent": "**\"M**ozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0; MSAppHost/1.0)\""}

with the bolded escaped invalid characters has to be dealt like this:

```
SELECT kafka_consume_begin('cdn_atomic_slices_json', 'cdn_stream',
    parallelism := 8, format := 'csv', quote := e'\x01', delimiter :=
    e'\x02', batchsize := 10000);
```

**Comment by vryzhov** [comment]
I am stuck with the same problem, but can't use the solution suggested here.  

The kafka topic is in JSON with certain elements coming from MaxMind database  Some of the "isp" entries of this database have double quotes inside the field. They are all properly escaped by backslashes upstream. For example,  I see `"isp":"OJSC \"Vimpelcom\""` when pulling the topic in kafkacat. 

The stream is defined with payload of type json: `CREATE STREAM ip_stream (payload json)`

Obviously I can't use `format = 'csv'` since the messages are not csv; `format = 'text'` is the only option, as `format = 'json'` is not supported by `COPY`. 

The problem is that by the time the payload reaches the stream, the backlashes disappear. As a result, the whole batch gets rejected since payload is not json anymore. The log file reports an error (notice the missing backslash '\' in CONTEXT:)

`LOG:  [kafka consumer] ip_stream <- kafka_maxMind.json failed to process batch, dropped 284 messages:`
`ERROR:  invalid input syntax for type json`
`DETAIL:  Token "Vimpelcom" is invalid.`
`CONTEXT:  JSON data, line 1: ...isp"::"OJSC "Vimpelcom...
        COPY ip_stream, line 54, column payload: "{"users":[{"events":1693,"asn":49724,"reconnected":false,"t..."
`  
The backslashes are stripped off somewhere along the way (some parsing/validation before the message is handed over to `COPY`, perhaps?). 

The `COPY` command with `format = 'text'` does not support `'escape'` parameter and I have no way to specify `\` as such (which may or may not help). 

Thank you.

**Comment by derekjn** [comment]
We should definitely just add a `'json'` format. I'm prioritizing this and should have a fix out today.

**Comment by derekjn** [comment]
Also, @vryzhov you can still use `format = 'csv'` with the above settings to work around this. In this case, `csv` is kind of a misnomer and has no actual relation to using commas as delimiters.

**Comment by vryzhov** [comment]
Hey @derekjn, Thanks for the fix and suggestions to use csv. I'll give it a try and report back.

**Comment by derekjn** [comment]
No problem @vryzhov, now you can just use `format := 'json'`.

**Comment by vryzhov** [comment]
I have just tested it and everything seems to be working just fine. Thanks for fixing it so quickly!

One small detail. 
I do not specify the delimiter in the call `pipeline_kafka.consume_begin()`, 
but every time I start the consumer, there is a warning message in the log:
`WARNING:  delimiter cannot be specified with format "json", ignoring`.

While we are on it, are there any plans to add the event timestamp to the log file?

**Comment by derekjn** [comment]
Ah, that is a harmless warning.

And log format is highly configurable in `pipelinedb.conf`. To prefix each line with a timestamp, you can do this in `pipelinedb.conf`:

```
log_line_prefix = '%t'
```

**Comment by vryzhov** [comment]
Awesome!  Thank you so much!!
